apiVersion: apps/v1
kind: Deployment
metadata:
  name: opsboard-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: opsboard-api
  template:
    metadata:
      labels:
        app: opsboard-api
    spec:
      containers:
        - name: api
          image: ghcr.io/rokobata510/opsboard-api:latest
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: opsboard-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opsboard-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: opsboard-config
                  key: POSTGRES_DB
            - name: DATABASE_URL
              value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: opsboard-secrets
                  key: JWT_SECRET