apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: opsboard
  region: eu-central-1
  version: "1.33"

availabilityZones:
  - eu-central-1a
  - eu-central-1b

managedNodeGroups:
  - name: opsboard-workers
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 2
    volumeSize: 20
    privateNetworking: false